package br.com.cleanhouse.adapter;

import br.com.cleanhouse.entity.UserProfileEntity;
import br.com.cleanhouse.dto.userprofile.fullregistration.UserProfileFullRegistrationRequestDto;
import br.com.cleanhouse.dto.userprofile.registration.UserProfileRegistrationRequestDto;
import br.com.cleanhouse.dto.userprofile.registration.UserProfileRegistrationResponseDto;
import br.com.cleanhouse.entity.AccessCredentialsEntity;
import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
public interface AdapterUserProfileMapper {
    UserProfileRegistrationResponseDto convertUserProfileRequestDtoToUserProfileResponseDto(UserProfileRegistrationRequestDto userProfileRegistrationRequestDto);
    UserProfileEntity convertUserProfileFullRegistrationRequestDtoToUserProfileEntity(UserProfileFullRegistrationRequestDto userProfileFullRegistrationRequestDto);
    AccessCredentialsEntity convertUserProfileEntityToAccessCredentialsEntity(UserProfileEntity userProfileEntity);
    UserProfileEntity convertUserProfileRegistrationRequestDtoToUserProfileEntity(UserProfileRegistrationRequestDto userProfileRegistrationRequestDto);
}
